### ISSUE TITLE
Generalized rewriting for applied morphisms

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#101]
If you have `k : ktree E A B`, i.e., `k : A -> itree E B`, then you can of course apply it `k a`. However, if you have an equation `e0 : eutt_ktree k k'` then you cannot `rewrite e0.`. Is there a way to define a `Proper` instance to rewrite on the left of a function application?

A related problem is to rewrite `f` in `interp f R t`. It seems we cannot write a `Proper` instance for dependently typed functions.

**Comment by gmalecha** [comment]
It seems like it should be possible to rewrite when the relation is a companion, right?

**Comment by Lysxia** [comment]
even if it is plain eutt there doesn't seem to be a way

**Comment by gmalecha** [comment]
I'm still not certain that I understand the issue. Is the problem with the first one solved if there is a symbol for application? Something like:

```coq
Definition apply {A B : Type} (f : A -> B) (x : A) : B := f x.
Instance Proper_apply {A B} : Proper (eutt_ktree ==> eq ==> eutt eq) (@apply A B).
```

(note that to use this, you would probably need to do something like `change (f x) with (apply f x)`).


As for the second one, the lack of dependency is unfortunately a limitation of setoid rewriting, but this sort of rewriting is generally quite hard. I think Jeremie at Yale has a library for doing some things like this though. It might be the case that as long as you keep the dependent type hidden, then you can rewrite. Does something like this work?

```coq
Definition Rnat {A B : Type -> Type} (l r : A ~> B) : Prop :=
  forall x (a : A x), l _ a = r _ a.
Instance Proper_interp {...} : Proper (Rnat A (itree B) ==> Rnat A (itree B)) (@interp A B _ _ _).
```

**Comment by Lysxia** [comment]
That looks reasonable. In fact I'm tempted to try and keep handlers, ktrees
and itree morphisms as types definitionally distinct from the type of
functions, forcing the use of apply functions which allow such rewriting.

**Comment by Lysxia** [comment]
I've made an attempt in branch `cleanup-interp-wip-inconsistent`, so that we could use `change (interp f t) with (apply_IFun (interp f) t).` to enable rewriting of `f`, but there is a universe inconsistency when `RecursionFacts` tries to import `KTreeFacts` and `MorphismsFacts`.
