### ISSUE TITLE
Duplicate names

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#112]
There are currently two modules named `ITree` (also `Eq`  and `Function`, but `ITree` is also the main module to import) which leads to warnings, e.g., https://github.com/vellvm/vellvm/issues/93

Shall we rename one of the two? It would be quite nicer if there was a way to require modules which didn't implicitly prefix them, which is the cause of the ambiguity.

**Comment by Zdancewic** [comment]
We should definitely do something about it -- the warnings are annoying.  I'm not sure what the best change is, through.  Maybe rename to `Core/ITreeDefinitions.v` (and similarly for the other conflicts) or something like that?

**Comment by gmalecha** [comment]
What is the source of the error? Is vellum not importing ITree with -Q?

**Comment by Lysxia** [comment]
It seems to come from coqdep but I'm not sure why it isn't triggered when we build our examples. You get the warning if you use

```
From ITree Require Import ITree. (* Matches both ITree.ITree and ITree.Core.ITree even with -Q *)
```

as opposed to

```
Require Import ITree.ITree.
```

**Comment by gmalecha** [comment]
We should file a bug on Coq for this. These two statements should be semantically equivalent.

**Comment by Lysxia** [comment]
OK I opened an issue https://github.com/coq/coq/issues/9839

This behavior is documented though, so it seems intentional, but having a stricter alternative seems preferable indeed.
