### ISSUE TITLE
Terminology and naming?

### ISSUE THREAD

**Issue by Zdancewic** [DeepSpec/InteractionTrees#118]
The library recently had `lift` and `liftE` renamed to `send` and `sendE`, but in discussion with @YaZko  and @Chobbes  we were thinking that "send" is too loaded.  Maybe we should pick a more neutral term, something like: "trigger"?  It might be common to have `Send` and `Receive` events and `send Send` and `send Receive` might look weird, whereas `trigger Send` and `trigger Receive` look more natural.

Similarly, we propose to rename the `Effects` subdirectory to `Events` and try to maintain the convention that the word "Event" means "data associated with a visible action that takes place at some moment in time" whereas an "Effect" is the result of interpreting the event to give it some semantics.  We would say that `interp_state` gives meaning to the events `Get` and `Put` to realize the state effects.

**Comment by Lysxia** [comment]
Alright, that sounds like a good idea to me.
