### ISSUE TITLE
Trace Definition

### ISSUE THREAD

**Issue by gmalecha** [DeepSpec/InteractionTrees#21]
I've got a few questions about the `is_trace` definition, I'm opening an issue for discussion purposes.

**Inductive vs CoInductive**
Why is `is_trace` `Inductive` rather than `CoInductive`? It seems like coinductive interaction trees should have coinductive traces. We can still use the definitions in `UpTo.v` to approximate the coinductive interaction trees with inductive approximations, and then we can use the current definition of `is_trace` to mostly talk about the the inductive interaction trees.

**Actions that can not Return**
I brought this up the in call on Friday. The current definition of trace doesn't work for interactions that have uninhabited results. For example, the simple effect (in the old style):
```coq
Variant Error : Type -> Type := RuntimeError (_ : string) : Error Empt_set.
```
In the current definition it is impossible to have a trace that includes `RuntimeError`, even if the interaction tree actually calls it, e.g. `Vis (RuntimeError "bad") (fun pf => match pf with end)` (the set of traces that this interaction tree contains only the empty (non-terminating) trace, i.e. `[], None`.

An alternative representation that addresses this problem would be something like:
```coq
CoInductive trace : Type :=
| Tau (_ : trace)
| Send (a : action) (_ : traceK (reaction a))
with traceK (t : Type) : Type :=
| TauK (_ : traceK t)
| Recv (_ : t) (_ : trace).
```
Here, I separate the call and reply actions so that I can represent calls that never return. You could replace both `Tau` and `TauK` with some notion of approximation, though (noting my first comment), I think it makes a bit more sense to do that separately.

A (potential) benefit of the ability to represent this sort of thing is that you should be able to prove a theorem that says that any approximated trace, i.e. trace ending with `None`, can be extended into a longer trace that is consistent with the original `itree`. To have this property, you would either need to add `Tau`s into the trace (like I did above), or add a `Diverge` constructor to both `trace` and `traceK` to represent divergent computations (which are *not* approximated).

**Comment by Lysxia** [comment]
`is_trace`  is `Inductive` to ensure that `spin`  has no nonempty traces. An alternative would be to add `Tau` in traces as you suggest, but then we would have to reason about traces "up to tau". The philosophical motivation for my way of defining `is_trace` is that a trace is what we observe of the program and that `Tau` is not observable.

You are right about the issue with `RuntimeFailure`, and separating the event `{ a : action &  reaction a }` into a `Send` and a `Recv` seems like the right way to make those traces more accurate.

**Comment by gmalecha** [comment]
> `is_trace` is `Inductive` to ensure that `spin` has no nonempty traces. An alternative would be to add `Tau` in traces as you suggest, but then we would have to reason about traces "up to tau". The philosophical motivation for my way of defining `is_trace` is that a trace is what we observe of the program and that `Tau` is not observable.

Ah, I see. In that case, you explicitly do not want the property that I was proposing. Is there an instance where it is not desirable to observe non-termination? If not, you could also big-step over finite traces using 
 a definition similar to

```coq
CoInductive trace : Type :=
| TDiverge (* infinite taus *)
| TVis (a : eff.(action)) (_ : eff.(reaction) a) (_ : trace)
| TEnd.

CoInductive is_trace : itree eff t -> trace -> Prop :=
| is_trace_done {v} : is_trace (Ret v) TEnd
| is_trace_diverge : is_trace spin TDiverge
| is_trace_tau {it it'} {t} : UnTaus it it' -> is_trace it' t -> it_trace it t
| ...
```

The downside of the definition by approximation that you have is you end up with `is_trace` meaning "is *a prefix of* a trace". But that does line up with your philosophical motivation since (using conventional machines) you can't observe things in the limit. Even if you don't change things, it might be good to make a note of these motivations within the file.

**Comment by Lysxia** [comment]
Indeed you cannot observe nontermination. More precisely, `Vis (RuntimeError _) (...)` and `Tau (Tau ...)` both have only the empty trace according to `is_trace`.

**Comment by bollu** [comment]
@Lysxia  this is quite unfortunate, since modelling of non-termination in loops is something that LLVM semantics allows to optimise away, AFAIU. Paging @tobig since he understands this much better than I do

**Comment by Lysxia** [comment]
It would be quite fine to add some way of distinguishing nontermination, that should be fairly easy to ignore when it doesn't matter (which is currently the case in our DeepSpec webserver work).

**Comment by Lysxia** [comment]
#56 and #66 provide technical answers to some of the questions here. In particular, Paul proved the correspondence between equivalence up to taus and a plain version of trace equivalence.

There are still some loose ends in this space, but let's postpone them in new, smaller scoped issues or later discussions.

I still like the `trace` definition in Gregory's opening comment here (and I can imagine that both the inductive and coinductive ones will find uses).
