### ISSUE TITLE
Extraction with new Effect structure?

### ISSUE THREAD

**Issue by Zdancewic** [DeepSpec/InteractionTrees#22]
I ran into a little bit of trouble when porting Vellvm to use the new factoring of interfaces into the record in Effect.v.  In particular, it seems that this version doesn't work well with extraction, since as far as I can tell, the Effect records gets erased.  I played around with trying to make the extraction work, but ran into universe inconsistency problems.

Any thoughts about how to fix that?

**Comment by Lysxia** [comment]
I totally forgot to check the extraction test, which is encountering a Coq internal bug. I'll see what I can do about it. The effect record only defines a type family, so it is expected that it gets erased, but practically that shouldn't be problematic; I may be missing some other issues.

**Comment by Zdancewic** [comment]
It looks like the Effect record doesn't include any information about the action field.  Here's what I get when I extract that file:

```
type __ = Obj.t

type coq_Effect =
| Build_Effect

type action = __

type reaction = __
```

**Comment by Lysxia** [comment]
I think that is fine (and we could even do without a `coq_Effect` type altogether. Anything of type `Type` or `_ -> Type` gets erased at runtime, since they're only type information.

**Comment by Zdancewic** [comment]
But the E parameter of ITree gets extracted as `action`, which is defined as nothing, so the event doesn't carry any information in the OCaml code.

**Comment by Lysxia** [comment]
But `__` is not nothing, it's `Obj.t` which is a type any OCaml value can be coerced to. Effect constructors have type `action E` (for some `E`), this type can't be written in OCaml because `action` is a function, so it gets replaced with `__` during extraction, but the runtime information isn't lost.

```
From ITree Require Import ITree.

Inductive IO : Type := Read | Write (n : nat).

Definition IO_reaction : IO -> Type := fun e =>
    match e with
    | Read => nat
    | Write _ => unit
    end.

Canonical Structure IOE : Effect := {|
  action := IO;
  reaction := IO_reaction;
  |}.

Definition example : itree IOE unit :=
  n <- liftE Read;;
  (liftE (Write n) : itree _ unit).

Require Extraction.
Recursive Extraction example.
```

**Comment by Zdancewic** [comment]
Sorry, what I meant was that I was confused because Build_Effect carries no data -- it's "action" field is erased to nothing.  I now see that this makes sense because the Build_Effect constructor isn't ever really used anywhere in the extracted code -- the underlying action value is coerced to the coq_Effect type wherever it is needed as such.
