### ISSUE TITLE
interp_prop is in the wrong place

### ISSUE THREAD

**Issue by Zdancewic** [DeepSpec/InteractionTrees#243]
For some reason `interp_prop` is in `[State.v](https://github.com/DeepSpec/InteractionTrees/blob/master/theories/Events/State.v)`  and similarly for the associated facts. These clearly belong somewhere else.

**Comment by Lysxia** [comment]
It seems to have moved to `interp_iforest` from Irene's PR. I did a bit of deduplication in #244.
