### ISSUE TITLE
Positive coinductive types are going to be deprecated

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#25]
For a description of the problem: https://github.com/coq/coq/pull/8670/files

We'll have to change `itree` to be a record type, with the variants described by a separate nonrecursive type, that I just happened to define to do some category theory in `Machine.v`.

**Comment by gmalecha** [comment]
I have code for this in the other repository.

https://github.com/gmalecha/coq-interaction-trees/blob/master/theories/Eff.v

It shouldn't affect too many things, but probably best to do earlier rather than later

**Comment by gmalecha** [comment]
Closed by #26
