### ISSUE TITLE
Paco Experiment

### ISSUE THREAD

**Issue by gmalecha** [DeepSpec/InteractionTrees#33]
We need to do a paco experiment to determine if it is sufficiently powerful to support the reasoning that we want to do.

Concretely, we decided that proving the unfolding lemma for `mfix` would be a good test. We can probably simplify this a little bit to just proving `interp f (bind c k) = bind (interp f c) (fun x => interp f (k x))`.

**Comment by gmalecha** [comment]
@Lysxia Were you looking into this? Have you gotten a chance to experiment?

**Comment by gilhur** [comment]
Hi all, 

I looked into this project.

The idea of defining 'mfix' is really cool!
I believe that paco should be able to prove everything that is true, but it may require careful thinking and more engineering.
I am happy to help you for this.

One thing I found in the project is that I think the following theorem in `Fix.v` is not true.
```
Theorem mfix_unfold : forall x, mfix x = body E (fun t => id) mfix x.
```
I think one can prove `mfix_unfold -> False` using the classical axiom.

My viewpoint is that `mfix` is a nice syntactic sugar for writing down a definition using `_mfix` and all reasoning should be done in terms of `_mfix`.

Also, I can try to prove the `interp_bind` lemma in MorphismsFacts.v, if you don't mind.
Also, I'd like to talk to you more about this project at POPL!

Thanks,
Gil

**Comment by gmalecha** [comment]
Thanks, Gil! Even a nudge in using Paco would be very appreciated. I'm interested in your comment about the up-to definition, but, regrettably, I haven't had the cycles to look at it lately.

**Comment by gilhur** [comment]
Hi Gregory,

I just finished proving a stronger version of `interp_bind`.
I used the axiom `bisim_eq` to make the proof simpler.
Also, I turned off `Set Primitive Projections` for the definition of `itree` because I don't know how to handle it properly.

Here is my code.
```
From Coq Require Import
     Program
     Classes.RelationClasses
     Classes.Morphisms
     Setoids.Setoid
     Relations.Relations
     Logic.JMeq Logic.EqdepFacts.

Inductive bisimF {E R} (bisim: relation (itree E R)) : relation (itree E R) :=
| Bisim_Ret: forall r, bisimF bisim (Ret r) (Ret r)
| Bisim_Tau: forall t1 t2, bisimF bisim (Tau t1) (Tau t2)
| Bisim_Vis: forall u (e1 e2: E u) k1 k2
                (EvtEQ: e1 = e2)
                (CtnEQ: forall v, bisim (k1 v) (k2 v)),
             bisimF bisim (Vis e1 k1) (Vis e2 k2)
.
Hint Constructors bisimF.

Lemma bisimF_mono : forall E R, monotone2 (@bisimF E R).
Proof. pmonauto. Qed.
Hint Resolve bisimF_mono : paco.

Definition pbisim {E R} r := paco2 (@bisimF E R) r.
Hint Unfold pbisim.

Definition bisim {E R} := @pbisim E R bot2.
Hint Unfold bisim.

Axiom bisim_eq: forall E R s t, @bisim E R s t -> s = t.

Lemma bisim_refl E R: forall s: itree E R, bisim s s.
Proof.
  pcofix CIH; intros.
  pfold. destruct s, observe; eauto.
Qed.

Lemma itree_unfold {E R}: forall (s:itree E R), s = go (s.(observe)).
Proof.
  intros. destruct s; auto.
Qed.

Lemma interp_unfold {E F R} {f : eff_hom E F} (t : itree E R) :
  interp f t = interp_match f (fun t' => interp f t') t.
Proof.
  setoid_rewrite (itree_unfold (interp f t)). simpl.
  setoid_rewrite <-itree_unfold. eauto.
Qed.

Lemma interp_ret {E F R} {f : eff_hom E F} (x: R):
  interp f (Ret x) = Ret x.
Proof.
  rewrite interp_unfold. reflexivity.
Qed.

Lemma interp_tau {E F R} {f : eff_hom E F} (t: itree E R):
  interp f (Tau t) = Tau (interp f t).
Proof.
  rewrite interp_unfold. reflexivity.
Qed.

Lemma interp_vis {E F R} {f : eff_hom E F} U (e: E U) (k: U -> itree E R) :
  interp f (Vis e k) = (x <- (f _ e);; Tau (interp f (k x))).
Proof.
  intros. rewrite interp_unfold. reflexivity.
Qed.

Lemma bind_unfold {E R} U t (k: U -> itree E R) :
  ITree.bind t k = ITree.bind_match k (ITree.bind' k) t.
Proof.
  rewrite (itree_unfold (ITree.bind t k)). simpl.
  setoid_rewrite <-itree_unfold. reflexivity.
Qed.

Lemma bind_ret {E R} U x (k: U -> itree E R) :
  Ret x >>= k = k x.
Proof.
  setoid_rewrite bind_unfold. reflexivity.
Qed.  

Lemma bind_tau {E R} U t (k: U -> itree E R) :
  Tau t >>= k = Tau (t >>= k).
Proof.
  setoid_rewrite bind_unfold at 1. reflexivity.
Qed.  

Lemma bind_vis {E R} U V (e: E V) (ek: V -> itree E U) (k: U -> itree E R) :
  Vis e ek >>= k = Vis e (fun x => ek x >>= k).
Proof.
  setoid_rewrite bind_unfold at 1. reflexivity.
Qed.

Lemma bind_assoc E A B C (t: itree E A) (k1: A -> itree E B) (k2: B -> itree E C):
  ((t >>= k1) >>= k2) = (t >>= fun r => k1 r >>= k2).
Proof.
  apply bisim_eq.
  revert A B t k1 k2.
  pcofix CIH. intros.
  destruct t, observe.
  - rewrite !bind_ret.
    eapply paco2_mon; [eapply bisim_refl|contradiction].
  - rewrite !bind_tau. eauto.
  - rewrite !bind_vis. eauto.
Qed.

Inductive prefix_clo {E R} (r: relation (itree E R)) : relation (itree E R) := 
| pbc_intro U (t: itree E U) k1 k2
      (REL: forall v, r (k1 v) (k2 v))
  : prefix_clo r (t >>= k1) (t >>= k2)
.
Hint Constructors prefix_clo.

Lemma prefix_clo_bisim_respectful E R: weak_respectful2 (@bisimF E R) prefix_clo.
Proof.
  econstructor; try pmonauto.
  intros. dependent destruction PR.
  destruct t, observe.
  - rewrite !bind_ret. eapply bisimF_mono; eauto using rclo2.
  - rewrite !bind_tau. eauto.
  - rewrite !bind_vis. eauto 7 using rclo2.
Qed.  

Lemma interp_bind {E F R S}
      (f : eff_hom E F) (t : itree E R) (k : R -> itree E S) :
   (interp f (t >>= k)) = (interp f  t >>= fun r => interp f (k r)).
Proof.
  apply bisim_eq.
  pupto2_init.
  revert R t k.
  pcofix CIH. intros.
  destruct t, observe.
  - rewrite interp_ret, !bind_ret. pupto2_final.
    eapply paco2_mon; [eapply bisim_refl|contradiction].
  - rewrite interp_tau, !bind_tau, interp_tau. eauto.
  - rewrite interp_vis, !bind_vis, interp_vis, bind_assoc.
    pupto2 (prefix_clo_bisim_respectful F S).
    econstructor. intros.
    rewrite bind_tau.
    pupto2_final.
Qed.  
```

I can make more time during and after the POPL meeting and am happy to look into more theorems and discuss how to prove them :)

**Comment by Lysxia** [comment]
Hi Gil, thanks a lot for this! Indeed you are right that `mfix_unfold` doesn't hold, it should be using the "up to Taus" equivalence (`theories/Eq/UpToTaus.v`). Reasoning about that equivalence is what we've found quite challenging, and the `seq` example with "up to 0" equivalence we've been discussing by email comes from that.

**Comment by gilhur** [comment]
Yes, I realized that reasoning about upto taus is quite tricky thanks to your example before.
But, now I think proofs can be tamed using upto techniques.
Could you let me know any tricky theorem about `eutt`?
I can try to prove it after the first round of the PLDI review process (since I am on the PC).

**Comment by gmalecha** [comment]
@gilhur @Lysxia I've opened a PR (#40) related to this with @gilhur 's definitions ported to avoid the need for the axiom. Using the axiom probably isn't much of a problem though.

**Comment by gilhur** [comment]
Hi, I just want to tell you that I almost finished most of the main theorems in the project without using the bisimilarity axiom, which I can probably pull request today for reviewing.
Note that I turned off the primitive projection just because I think it makes automation better.

Regarding primitive projections, now I understand the ideas behind it and tried a version with it, which worked the same at high level but working with it was less convenient.

**Comment by gmalecha** [comment]
Thanks, @gilhur! I was wondering where the pupto tactic is defined. It doesn't seem to be defined in the opam version of Paco (did I miss it?), though it does seem to be mentioned in some of the pull requests.

**Comment by gilhur** [comment]
I just added a PR, which includes proofs of `interp_bind` and `homFix_is_interp`.
It also includes `paco2_respectful.v`, which I will add to the main paco repository soon.

**Comment by gmalecha** [comment]
This seems resolved.
