### ISSUE TITLE
Separate some of the core effects?

### ISSUE THREAD

**Issue by gmalecha** [DeepSpec/InteractionTrees#34]
Whenever you import `Effects`, you get a lot of effects. This can be convenient in some instances, but can also be very painful, for example if someone defines their own collection of effects and wants to use the name `Get`.

I'd like to propose separating some of the effects so that it is possible to `Require Import` just the sum effect (which there is no reason to ever overload) and get the definition of `do`.

What do you guys think?

**Comment by bcpierce00** [comment]
Sounds good to me.

**Comment by Lysxia** [comment]
The current situation for this issue is that the sum effect was split out (which I think is the most important bit), but the "standard" set of effects still needs reorganization.

**Comment by Lysxia** [comment]
Fixed in #106
