### ISSUE TITLE
Rename 'do' ?

### ISSUE THREAD

**Issue by Zdancewic** [DeepSpec/InteractionTrees#38]
Currently the record that we use for the itree CoInductive uses `do` as the constructor name, but I was running into some issues writing tactics that look for `do` because it is also an Ltac keyword.  Should we change `do` to `go` or something else?  

(It could also be that the tactics I'm trying to write should be written in a different way, which wouldn't run into the conflict.)

**Comment by gmalecha** [comment]
It makes sense to rename. Let's do it.

**Comment by Zdancewic** [comment]
Ok -- I'll rename it to 'go' for now.  I don't think that introduces any clashes.

**Comment by Zdancewic** [comment]
OK -- there were two different uses of `do`.  

- I changed the constructor from `do` to `go` in itree
- I changed the word `do` to `lift` for the OpenSum stuff.  (Maybe `lift` should be something better?)
