### ISSUE TITLE
Use ExtLib's monad type classes?

### ISSUE THREAD

**Issue by gmalecha** [DeepSpec/InteractionTrees#6]
Do people have opinions about pulling in ExtLib's typeclasses for monads?

**Comment by bcpierce00** [comment]
I like the ExtLib monads, and we use them all the time internally.  (I’ll like them even better when they allow binding patterns — can they do that, yet?)

But there’s some feeling that, since there isn’t a community-standard monad library at the moment, we should try not to force people to use the one we prefer.  Would it be easy to use ExtLib internally but leave enough room for clients to make different choices?

   - B

**Comment by gmalecha** [comment]
Clients can always add their own instances for other type classes if they wish to use another library. By using ExtLib here we would require them to install ExtLib. We could (with other library writers) separate the monads from ExtLib and depend specifically on them. If we can get buy-in from other authors, we can prevent fracturing.

There was a PR to support binding patterns, I need to release a new opam version with suppoet for it.

**Comment by bcpierce00** [comment]
> Clients can always add their own instances for other type classes if they wish to use another library. By using ExtLib here we would require them to install ExtLib. We could (with other library writers) separate the monads from ExtLib and depend specifically on them. If we can get buy-in from other authors, we can prevent fracturing.

I think a dependency on ExtLib is not terrible — it’s just one more OPam install.  

Having said that, I think a separate monad library might get better uptake in the community (especially if it were structured to make it a little easier to find things — I always find the current organization a bit hard to navigate when I’m looking for things).
> There was a PR to support binding patterns, I need to release a new opam version with suppoet for it.
> 
> 

Great!

   - B

**Comment by gmalecha** [comment]
@bcpierce00 It would be great to hear any suggestions that you have about the ExtLib monads, especially if we split it into another library.

**Comment by bcpierce00** [comment]
Just simplifying the directory structure would go a long way!  Also adding a tiny bit of documentation — just an index of what’s there in the README file would be a big help.

**Comment by gmalecha** [comment]
This is done.
