### ISSUE TITLE
Notation for `bind` in Core.v?

### ISSUE THREAD

**Issue by Zdancewic** [DeepSpec/InteractionTrees#61]
There might be a slight issue with the notations defined in Core.v -- I believe that the intention is to use the notations for ITree.bind, but they seem to be using the extlib `bind` field of the Monad typeclass.  This might cause some issues.  We probably should define notation that mentions `bind` without qualifying it.  Perhaps we just need to add `Itree.bind` in the notation here?

(This problem seems to crop up in some difference between Coq 8.8.2 and 8.9 when compiling the MorphismsFacts.v file.)

**Comment by Lysxia** [comment]
Right, we should fix these notations.

**Comment by Lysxia** [comment]
Fixed in https://github.com/DeepSpec/InteractionTrees/commit/980126e4645d508eb916e3d01fc2a048718182ca
