### ISSUE TITLE
Determine if we can make interp equivalent to translate when using `Vis e Ret`

### ISSUE THREAD

**Issue by gmalecha** [DeepSpec/InteractionTrees#73]
This would require that we only introduce a `Tau` constructor for `Vis` if the effect interpretation is `Ret`.

**Comment by gmalecha** [comment]
I gave this a try and the definition isn't that much more complicated. I need to understand a bit more about paco proofs to update the lemmas though.

```coq
Definition interp {E F : Type -> Type} (h : E ~> itree F) :
  itree E ~> itree F := fun R =>
  cofix interp_ t :=
    handleF interp_
            (fun _ e k =>
               match (h _ e).(observe) with
               | RetF r => Tau (interp_ (k r)) (* only insert Tau if you are interpreting immediately to a Ret *)
               | TauF z => Tau (ITree.bind z (fun x => interp_ (k x)))
               | VisF e k' => Vis e (fun x => ITree.bind (k' x) (fun x => interp_ (k x))) (* don't inject the extra Tau *)
               end)
            (observe t).
```

This this means that `eq_itree (translate f it) (interp (fun _ e => Vis (f _ e) (fun x => Ret x)) it)` which would allow us to change this equation into a definition. As long as we reason using equational rewriting, there shouldn't be any impact on users.

**Comment by gmalecha** [comment]
@Lysxia Any initial thoughts on this? I think the proofs for `interp` would be a little bit more complex, but we would get all the `translate` proofs "for free".

**Comment by Lysxia** [comment]
This looks reasonable, for sure.

**Comment by Lysxia** [comment]
I gave that a quick try but couldn't figure out how to fix the proofs.

You can repackage this `match` into a `bind_delay`, which is equivalent to `bind`, but inserts a `Tau` if `Ret` is the first constructor.

**Comment by Lysxia** [comment]
I now think that, as far as this library is concerned,  `Tau`'s are too finicky so the library should try to hide `Tau` (and paco) behind `eutt` as much as possible. This seems to add too much complexity for the ability to use  `eq_itree` or `eq` in non-visible ways. So let's close this, but I'm open to further related suggestions.
