### ISSUE TITLE
Make `go` a coercion

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#76]
I wonder whether that would work well, so we wouldn't need separate notations for `Vis` and `VisF`.

**Comment by gmalecha** [comment]
One issue that I often have with coercions is that they get in the way of unification problems. But it is probably worth trying.

**Comment by Lysxia** [comment]
After a quick attempt, I run into the problem that `go` doesn't satisfy the uniform inheritance condition, and I suspect any workaround that involves a separate `Definition` equal to `go` is going to raise issues with unification that you mention.

I opened a Coq issue to clarify a few points in the Coq manual on coercions, but this may lead us nowhere https://github.com/coq/coq/issues/9696

**Comment by Lysxia** [comment]
There doesn't seem to be a way around the uniform inheritance condition.
