### ISSUE TITLE
Remove `_observe`

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#77]
Now we have `observe` which is a `Definition` synonym for the real primitive projection `_observe`, presumably because it makes it easier to control reduction. I believe that we can remove this layer, possibly structuring the proofs a bit differently.

**Comment by Lysxia** [comment]
A naive attempt leads to situations where we unfold too much. For instance in quite a few places we have `observe (t >>= k)` which unfold unnecessarily to `observe (match observe t with ... end)`. While the proofs are fixable, the result is really fragile and hard to maintain. We should find a more principled pattern to organize coinductive proofs.

Another subtle point is that in the "core language", primitive projections are always applied, but the "surface language" allows `observe` to be used as an expression on its own. So in the surface language `observe` can stand for two things: `observe` the primitive projection, which must be applied, and a wrapper `#observe` which unfolds to `(fun x => observe x)` and is a Gallina expression on its own. This leads to quite cryptic failures if we're not careful.

- With the current definitions, where `observe` is a definition around `_observe`, when we want to unfold `observe`, we have to `unfold observe, _observe.` I conjecture that this can be avoided by eta expanding the definition of `observe`: `observe x := _observe x` (which will use the real primitive projection), instead of `observe := _observe` (which will use the wrapper).

- Some proofs rely on a `Proper` lemma for `observe`, which, as explained above, would desugar to `#observe` (i.e., `fun x => observe x`) if we make `observe` the actual primitive projection. But in  those proofs, we want to rewrite under `observe` the primitive projection, and Coq won't pick up the instance for the `#observe` wrapper.

To conclude:

1. Allowing a primitive projection `_observe` to be used as a standalone expression is a mistake. It should always be applied, and Coq should enforce this.  I'll look for an option, and if there isn't one I'll report a bug.

2. It might still be useful to have a real function representing `_observe` to be used as an expression. But it should have a different name; the right definition must be eta-expanded: `observe x := _observe x`. One use case is that it can carry a `Proper` instance for rewriting as we do now. Another is to pass it to higher order functions.

3. eta-expansion of primitive records and projections in general feels like an antipattern to me. I can't quite put my finger on the problem here, but it's like using an axiom where we don't need it, even though it's allowed.

4. I hope that we will be able to streamline our proofs and remove that "antipattern" by refactoring our cofixpoints as anamorphisms.

**Comment by gmalecha** [comment]
I don't think that eta expansion is definitional for recursive records, but maybe that is not what you are saying.

**Comment by gmalecha** [comment]
Maybe it makes sense to just keep the definition.

**Comment by Lysxia** [comment]
Indeed I mean that even  `eq_itree eq t (go (observe t))` seems superfluous in a way.

**Comment by Lysxia** [comment]
Anyway, the conclusion is that `observe` is useful but it had the wrong definition. The right way to wrap a primitive projection is by applying it explicitly.

https://github.com/DeepSpec/InteractionTrees/commit/3c01fceb603f106f72235e87a2807776eb31e810#diff-870c0721d112f0bdb277c1e4de9d81a1R74
