### ISSUE TITLE
CI: auto cancel build of obsolete branches

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#78]
There is an option for it in travis: https://docs.travis-ci.com/user/web-ui/#sts=Auto%20cancel%20branch%20builds%20#

**Comment by Lysxia** [comment]
Only @Zdancewic has the permissions for this.

**Comment by Zdancewic** [comment]
OK -- I set that flag (and the analogous one for pull requests) on the travis page.
