### ISSUE TITLE
Project description on Github

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#82]
Currently the front page says "Formalization of the Interaction Tree Datatype in Coq" but, well, that doesn't tell a whole lot that's not in the name of the project itself.

The subtitle of our paper seems like a good candidate: "Representing Recursive and Impure Programs in Coq".

I don't have the administrative permissions to do this myself.

**Comment by gmalecha** [comment]
Rather than "Representing ..." maybe we should say "A library for representing...."?

**Comment by Zdancewic** [comment]
I changed it to "A Library for..."
