### ISSUE TITLE
Some proofs are slow

### ISSUE THREAD

**Issue by Lysxia** [DeepSpec/InteractionTrees#83]
With the further split of some `eq_itree` properties into `Eq/Shallow.v` (typically as `observing eq`), it sometimes takes up to 10s to use those "shallow" equivalences for rewriting. Some examples of this are marked as TODO.

The `observing` pattern is common enough that it would be a shame to drop this module for performance reasons.

**Comment by gmalecha** [comment]
Can you reference specific tactic lines that take a long time? I might have some thoughts about them.

**Comment by Lysxia** [comment]
You can take a look at `rewrite ret_bind.` in `Morphisms.unfold_interp`, and `rewrite unfold_bind.` in `Morphisms.interp_bind`.

**Comment by Lysxia** [comment]
It looks like these quoted proofs are no problem now. I'll close this and open more specific issues for other slow parts.
