### ISSUE TITLE
Split up Morphisms.v

### ISSUE THREAD

**Issue by Zdancewic** [DeepSpec/InteractionTrees#84]
We need to break up Morphisms.v into:

- translation
- itree handlers
- effectful interperters

**Comment by gmalecha** [comment]
What are the types of these? I'm not familiar with the distinction between "itree handlers" and "effectful interpreters". Is this just whether or not the handler is monadic?

@Zdancewic What are your thoughts on #73 ? If we did that, we'd get to drop `translate`.

**Comment by Lysxia** [comment]
The way I did it in #93 is to separate the categorical structure of handlers from the definitions of `translate` (which might get dropped), `interp`, `mrec`.

**Comment by Lysxia** [comment]
Between `Interp`, `Handler` and `Recursion` this seems in pretty good shape.
