### ISSUE TITLE
Create interface(s) for the main library

### ISSUE THREAD

**Issue by Zdancewic** [DeepSpec/InteractionTrees#85]
Decide how to explain the main interface.

Q: Do we break it into a couple of parts?  Itree Core / Interpreters / KTrees / etc., or put it all in one.
Either way, we should provide guidance and documentation about how to read the interfaces.

**Comment by gmalecha** [comment]
Personally, I like small and independent files and then groups of similar files re-exported. While these files can be useful to read, it might be better to write a single file that imports everything (either up front or when it is first introduced) and then uses `Print` to introduce a concept. This decouples the desire to write and prove things in close proximity from the need to introduce them together. It also completely hides the proofs, which for most clients are not necessary, certainly not necessary for a first walk-through of the library.

Something like:

```coq
Require Import ....

(* * Interaction Trees
 * Interaction trees represent ....
 *)
Print itree.
(* ... include the output here ... *)

(* Interaction trees form a monad *)
Print Monad_itree.
(* ... include the output here ... *)

(* this allows us to write itrees in a natural way using monad notation. Here is a very simple program that...
 *)
Definition foo := ....

(* One of the most interesting things about itrees is that they admit a fixpoint combinator.
 * (we will discuss the implementation of mrec later)
 *)
About mrec.
(* ... *)

(* Using `mrec` we can define some more interesting programs. *)
Definition fib := .... 

(* and, we can actually compute with them. *)
Eval vm_compute in force 100 (fib 10).

(* because interaction trees form a monad we can define the kleisli category. We call these `ktree` for "continuation trees" since they are the type of continuations to `Vis` (conveniently, you can also think of the `k` as standing for Kleisli.
 *)
Print ktree.

(* ktrees form a traced symmetric monoidal category, which is kind of intimidating at first, but it really just means that it:
1. is a category, i.e. has identities and compositions (with appropriate laws).
*)
Print ktree_cat. (* or maybe About ktree_compose. About ktree_id. *)
(* also show the monad laws *)

...

```

**Comment by Lysxia** [comment]
Right now in `theories/Simple.v`  I give a quick summary of the main functions and offer an opaque version of `eutt` with lemmas, that should be sufficient to reason about termination of general recursive functions. For coinduction we have to dive deeper.
 https://github.com/DeepSpec/InteractionTrees/blob/5be1bf3d57d5c4d83c8e5dd4716e821f285cf783/theories/Simple.v

**Comment by gmalecha** [comment]
What is the status of this? Is it merged? Can we close it?

**Comment by Lysxia** [comment]
I think so. The documentation is a bit light on the coinduction side but we're actively working with Gil on it so it can be considered a separate issue/line of work.
