### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by liyishuai** [DeepSpec/InteractionTrees#87]
Despite the rapid development, some release 0.1.0 would be convenient for heavy users _e.g._ DeepWeb. https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase

**Comment by gmalecha** [comment]
I would actually be tempted to suggest that what we have (or plan to have) is worthy of a 1.0.0 release. Unless we adopt Haskell versioning scheme :-)

**Comment by liyishuai** [comment]
Indeed, the "First release" project looks much more than a v0.1.0 looks like.

**Comment by Lysxia** [comment]
If I read this right we should actually have been doing 0.\* releases since the start. So I propose to make 0.1.0 release right after #114 since there are already projects depending on this library in the current state, and move the remaining milestones to 1.0.0.

**Comment by Lysxia** [comment]
It looks like we're in good shape for 1.0.0 now already.

**Comment by liyishuai** [comment]
I've drafted coq/opam-coq-archive#608, which depends on a release in this repo.

**Comment by Lysxia** [comment]
Let's make a release this afternoon/evening.

**Comment by Zdancewic** [comment]
Sounds great!

**Comment by Lysxia** [comment]
Here we go https://github.com/DeepSpec/InteractionTrees/releases/tag/1.0.0
